### ISSUE TITLE
Compilation fail

### ISSUE THREAD

**Issue by rolfsimoes** [e-sensing/sits#3]
Hello @vwmaus!

I am getting an error when compile sits from scratch:

* installing to library ‘/.../R_libs’
* installing *source* package ‘sits’ ...
g++  -I/usr/share/R/include -DNDEBUG      -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
** libs
RcppExports.cpp:4:18: fatal error: Rcpp.h: No such file or directory

Some idea about how to solve this?

**Comment by rolfsimoes** [comment]
Solved here!

Thanks!

**Comment by gilbertocamara** [comment]
Oi Rolf


Você poderia entrar no zoom: http://https://zoom.us/j/569732259 ?


Gilberto

====================================================================
Prof. Dr. Dr.h.c. Gilberto Camara
National Institute for Space Research (INPE), Brazil
http://www.dpi.inpe.br/gilberto
=====================================================================

On 03.08.2017 at 16:32:53 , Rolf Simoes (notifications@github.com) wrote:

Hello @vwmaus <https://github.com/vwmaus>!

I am getting an error when compile sits from scratch:

   - installing to library ‘/.../R_libs’
   - installing *source* package ‘sits’ ...
   g++ -I/usr/share/R/include -DNDEBUG -fpic -g -O2
   -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time
   -D_FORTIFY_SOURCE=2 -g -c RcppExports.cpp -o RcppExports.o
   ** libs
   RcppExports.cpp:4:18: fatal error: Rcpp.h: No such file or directory

Some idea about how to solve this?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/e-sensing/sits/issues/3>, or mute the thread
