### ISSUE TITLE
Develop a new version of sits_regularize()

### ISSUE THREAD

**Issue by gilbertocamara** [e-sensing/sits#584]
The current version of sits_regularize() is based on the package `gdalcubes`. However, we have seen that `gdalcubes` sometimes produces incorrect results when dealing with large data sets.  The error appears when running `gdalcubes` in parallel with large number of threads. These errors are hard to reproduce and to provide a minimum working example for the `gdalcubes` developers. Since `gdalcubes` is mostly in C++, it is hard to trace the source of errors. Considering that `sits` already has a lot of the functions that `gdalcubes` provides, such as building catalogues and operations on cubes, it is advisable to invest on a sits_regularize() function that does not rely on `gdalcubes`. The current version of the `terra` package provides the functions required by regularizing cubes. Thus, converting `sits` to use `terra` instead of `gdalcubes` will be a useful improvement.

**Comment by appelmar** [comment]
Hi Gilberto and all, the errors are indeed hard to reproduce and I agree that using `terra` would probably be much easier to maintain for you. I just wanted to let you know that I am working on an alternative parallelization strategy for gdalcubes using _processes_ instead of _threads_, hoping that this will eliminate any potential race conditions and stack overflows. In any case, let me know if I can help to make `sits_regularize()` more stable.

**Comment by appelmar** [comment]
Yes, many thanks, I'd be very interested to look at the example. Sharing a script would be enough, I can try to reproduce with my own AWS machine. This really sounds like a different error, which we have not discussed in our meeting in November.
