### ISSUE TITLE
Is there a way to speed up sits_regularize() ?

### ISSUE THREAD

**Issue by kamaulindhardt** [e-sensing/sits#587]
**Hi Gilberto and colleagues**,

I was wondering if there is a way to speed up the regularization of data cubes? For some reason, it takes me hours to run the regularization of this single sentinel tile for a P1M with the original period being 2018-07-01 – 2020-09-30. 

Am I doing something wrong?

```
# # --- Data cube from AWS of the AOI, Nairobi, central Kenya
nrb_kenya_cube <- sits_cube(
      source = "AWS",
      collection = "sentinel-s2-l2a-cogs",
      bands = c("B02", "B03", "B04", "B08", "B11", "CLOUD"),
      tiles = "37MBU",
      start_date = "2018-07-01",
      end_date = "2020-09-30")
```

```
# # --- Regularise the nrb_kenya_cube of AOI
nrb_kenya_regular_cube <- sits_regularize(
          cube       = nrb_kenya_cube,
          output_dir = data_path,
          res        = 20,
          period     = "P1M",
          agg_method = "median",
          cloud_mask = TRUE,
          multicores = 6)
```

**Comment by gilbertocamara** [comment]
Dear @kamaulindhardt, I replicated your script in my local machine in Brazil. It took about two hours to generate two years of data. Considering that the data comes from an AWS server in Oregon, such time looks reasonable to me. That said, we are working on an improved version of sits_regularize(), which will be faster than the current one. 

I also suggest that you use "least_cc_first" rather than "median" as the aggregation method. The reason is that the Sentinel-2 cloud mask has problems and the "median" value may be a cloud value. Using "least_cc_first" one assumes that the image with the least cloud cover is the one whose pixel values are the most likely to be correct.

We also suggest that you try "P16D" (16 day intervals) as the period instead of "P1M" (one month). For us, this period gets better results.

**Comment by kamaulindhardt** [comment]
Dear Gilberto,


Thank you for this elaborate explanation, it's very appreciated! I will certainly try it out.
