### ISSUE TITLE
Possible Bug in cloudmasking

### ISSUE THREAD

**Issue by NvNorsinski** [e-sensing/sits#860]
Hello,
recently I processed with `sits_regularize` some data. As aggregation period 15 day was used. When I have a view at the resulting TIFF files some qustions come to my mind. What I would expect is, the resulting composites would may have missing values for areas which are cloudy for the whole period. This can be seen in certain areas in the pictures. But in addition river (Fig. top) and cropland areas (Fig. bottom) have also no data. What seems to me as if these areas are wrongly recognised as clouds.
Additionally in the description of the  `sits_regularize` method it is written, it will use the first valid pixel for aggregation. I think the cloudmasking does not work perfectly espacially at the border of thin cirrus clouds. Wouldn't it be better to calculate the pixel by the median of the valid pixels in the time period?, or at least to have an option to change the aggregation method. 

```
s2_cube <- sits_cube(source = "AWS",
                     collection = "SENTINEL-S2-L2A-COGS",
                     tiles = c("32TNT" ,"33UXP"),
                     bands = c("B02", "B03","B04","B05", "B06", "B07", "B08", "B8A", "B11", "B12", "CLOUD"),
                     start_date = as.Date("2019-03-01"),
                     end_date = as.Date("2019-10-30")
)



gc_cube <- sits_regularize(cube          = s2_cube,
                           output_dir    = file,
                           period        = "P15D",
                           res           = 10, 
                           multicores    = 13)
```

![sitsPNG](https://user-images.githubusercontent.com/36541056/192267975-9c5952e7-cfe0-448f-aaf7-58dcd0f9b6f4.PNG)

![sitsUXP](https://user-images.githubusercontent.com/36541056/192268041-27817555-d734-4c15-b91e-d108481a6920.PNG)

**Comment by gilbertocamara** [comment]
Hi @NvNorsinski, `sits` relies on the cloud information provided by ESA, which is available as the `CLOUD` band in the collection. So, there might be errors on this algorithm, since all cloud detection algorithms have problems. As for the aggregation method, we found out that option for the first non-cloudy pixel works better than the `median` method. Consider one period with more cloudy values than cloudy ones for the same pixel. The median will give a bad result.

**Comment by gilbertocamara** [comment]
We will consider including an option for the `aggregation method` in future versions of `sits`. Consider that, even if the time series has some missing values or some errors due to bad cloud detection, `sits` will interpolate these missing values based on valid values in the series. Thus, in situations where there is even a small number of valid pixels in the series, there will still be a reasonable result, which should be better than a temporal aggregation that collapses all times.

**Comment by gilbertocamara** [comment]
Dear @NvNorsinski I checked your script. It works fine, your problem has to do with lots of clouds in some dates. Please try to run some classification on your data and inform us about the result.
