### ISSUE TITLE
Requesting to pass MPC token to bypass rate-limits 

### ISSUE THREAD

**Issue by felixg3** [e-sensing/sits#945]
**Describe the new API function requested**
I would like to be able to pass my MPC API token to have better rate limits
**Associated sits API function**
sits_cube()
https://planetarycomputer.microsoft.com/docs/concepts/sas/
https://planetarycomputer.microsoft.com/api/stac/v1/

**Additional context**
Add any other context about the new function here.

**Comment by OldLipe** [comment]
Hi @felixg3,

We have added the option of including your MPC token in sits version 1.4.0 (currently under development). To install the current development version, please use: `devtools::install_github("e-sensing/sits@dev")`. 

To include your longer-lived token you need to add an environmental variable with the token as follows: `Sys.setenv("MPC_TOKEN" = "YOUR-TOKEN")`. Including your longer-lived token should solve the problem of long delay in accessing data from MPC. Since regularization takes a long time, a short lived token will expire before the operation is completed leading to the problem you reported. Using a longer-lived token will in general solve the problem.

**Comment by felixg3** [comment]
Got that! Unfortunately, it doesn't work for me, but now I am at least getting an error for rate limits... When in the cloud at MPC, I cannot write sits_cube_copy() to an object like storage_container(bl_endp_key, "container"), it has to be a local path? 
bl_endp_key <- storage_endpoint("https://<location>.blob.core.windows.net/", key="<key>")

**Comment by gilbertocamara** [comment]
Hi @felixg3, sits_cube_copy() requires a local directory. Could you please raise an issue so that sits_cube_copy() is able to write to a storage container?
